### ISSUE TITLE
Wallet Backup

### ISSUE THREAD

**Issue by bitwalt** [kaleidoswap/desktop-app#10]
**Description:** Provide a backup option for the wallet in the settings.

**Tasks:**

- [X] - **Backup Button:** Add a button in the settings to initiate the wallet backup process.
- [ ] - **Backup Logic:** Implement backup functionality that encrypts and save the backup after each trade/payment
- [ ] - **Cloud Storage:** Provide an option to store the encrypted backup on the cloud (?)
